const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.video,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY
	];
};
self.C3_JsPropNameTable = [
	{TOMBOLMATERI: 0},
	{BG: 0},
	{MATERI: 0},
	{Sine: 0},
	{PROFIL: 0},
	{GAME: 0},
	{Touch: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Video: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{BACKHOME: 0},
	{DragDrop: 0},
	{Sprite14: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{pngtreeblueskywhitecloudsskytransparentcloudsfreecutoutcloudshdimage_: 0},
	{Solid: 0},
	{dgameassetsbackgroundplatforms260nw2470295023removebgpreview: 0},
	{Platform: 0},
	{kenali3jenisdangejalasakitmatapadakucingpeliharaanhalodocremovebgpreview: 0}
];

self.InstanceType = {
	TOMBOLMATERI: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	MATERI: class extends self.ISpriteInstance {},
	PROFIL: class extends self.ISpriteInstance {},
	GAME: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	BACKHOME: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	pngtreeblueskywhitecloudsskytransparentcloudsfreecutoutcloudshdimage_: class extends self.ISpriteInstance {},
	dgameassetsbackgroundplatforms260nw2470295023removebgpreview: class extends self.ISpriteInstance {},
	kenali3jenisdangejalasakitmatapadakucingpeliharaanhalodocremovebgpreview: class extends self.ISpriteInstance {}
}